{{- if .Values.canary.enabled }}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ template "podinfo.fullname" . }}
  labels:
    app: {{ template "podinfo.name" . }}
    chart: {{ template "podinfo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  provider: appmesh:v1beta2
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ template "podinfo.fullname" . }}
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name:  {{ template "podinfo.fullname" . }}
  service:
    port: {{ .Values.service.port }}
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 5
  skipAnalysis: true
{{- end }}