# Default values for podinfo.
image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: 5.0.0
  pullPolicy: IfNotPresent

podAnnotations: {}

service:
  enabled: false
  type: ClusterIP
  port: 9898

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpu: 80
  memory: 512Mi

canary:
  enabled: true

resources:
  limits:
  requests:
    cpu: 100m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: ""
fullnameOverride: ""

logLevel: info
backend: #http://backend-podinfo:9898/echo
backends: []
message: #UI greetings

faults:
  delay: false
  error: false

httpServer:
  timeout: 30s
